import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.ticker import LogFormatterMathtext


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot the iteration comparison for Fornasini-Valcher Example 3."
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(__file__).with_name("comparison_results.csv"),
        help="CSV generated by comparison_sweep.jl.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Destination PDF path.",
    )
    return parser.parse_args()


def load_results(path: Path) -> tuple[list[float], list[int], list[int]]:
    with path.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream))
    rows.sort(key=lambda row: float(row["epsilon"]))
    epsilon = [float(row["epsilon"]) for row in rows]
    rdp_updates = [int(row["rdp_updates"]) for row in rows]
    fv_updates = [int(row["fv_updates"]) for row in rows]
    return epsilon, rdp_updates, fv_updates


def main() -> None:
    args = parse_args()
    epsilon, rdp_updates, fv_updates = load_results(args.input)

    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.size": 8.5,
            "axes.labelsize": 9,
            "legend.fontsize": 7.5,
            "xtick.labelsize": 8,
            "ytick.labelsize": 8,
            "pdf.fonttype": 42,
        }
    )
    figure, axis = plt.subplots(figsize=(3.35, 2.45))
    axis.loglog(
        epsilon,
        rdp_updates,
        color="#0D3B8E",
        marker="o",
        linewidth=1.5,
        markersize=4.5,
        label="Proposed RDP",
    )
    axis.loglog(
        epsilon,
        fv_updates,
        color="#6B9AC4",
        marker="s",
        linestyle="--",
        linewidth=1.5,
        markersize=4.5,
        label="Fornasini-Valcher recursion",
    )
    axis.set_xlabel(r"Cost parameter $\epsilon$")
    axis.set_ylabel("Number of value updates")
    axis.set_xticks([1e-4, 1e-3, 1e-2, 1e-1])
    axis.set_yticks([1, 10, 100, 1000, 10000])
    axis.xaxis.set_major_formatter(LogFormatterMathtext())
    axis.yaxis.set_major_formatter(LogFormatterMathtext())
    axis.grid(which="major", color="#D7DCE2", linewidth=0.6)
    axis.legend(loc="upper right", frameon=True, edgecolor="#B8BEC7")
    figure.tight_layout(pad=0.35)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    figure.savefig(
        args.output,
        format="pdf",
        bbox_inches="tight",
        metadata={"Creator": "matplotlib", "Title": "Iteration comparison"},
    )


if __name__ == "__main__":
    main()
